version: '3.9'

services:
  web:
    image: viktoriyabelnitska/wvika:latest
    container_name: web
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app

    ports:
      - "5000:5000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - ./certbot:/var/www/certbot
    networks:
      - networkDC
      

  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - networkDC

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
      - "5433:5432"
    volumes:
      - ./certbot:/var/www/certbot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/ssl
    networks:
      - networkDC

volumes:
  pgdata:

networks:
  networkDC:
    external: true
