name: Auto Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Docker login
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build image
      run: docker build -t viktoriyabielnitska/wvika:latest .

    - name: Push image
      run: docker push viktoriyabielnitska/wvika:latest

    - name: Connect to server and deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /home/ec2-user/WVika
          docker-compose down
          docker image rm viktoriyabielnitska/wvika:latest || true
          docker system prune -f || true
          docker pull viktoriyabielnitska/wvika:latest
          docker-compose up -d
